From 6bb17ef7c9e8173261e7002a3feed06027c04091 Mon Sep 17 00:00:00 2001
From: Chris Feist <cfeist@redhat.com>
Date: Tue, 3 Mar 2015 15:24:04 -0600
Subject: [PATCH 07/10] Show error if a bad password is used and node is
 already authorized

---
 ricci/ccs/ccs | 16 ++++++++++++++++
 1 file changed, 16 insertions(+)

diff --git a/ricci/ccs/ccs b/ricci/ccs/ccs
index 6e6a11c..9cd8072 100755
--- a/ricci/ccs/ccs
+++ b/ricci/ccs/ccs
@@ -2436,6 +2436,18 @@ def check_cluster_conf():
     else:
         print "All nodes in sync."
 
+# If success is "10" (RRC_AUTH_FAIL) then we have already been
+# authenticated, but we used a bad password
+def verify_authentication_password(dom):
+    ricci =  dom.getElementsByTagName("ricci")
+    if len(ricci) > 0:
+        if ricci[0].getAttribute("success") != "0":
+            return False
+        else:
+            return True
+    print "Error: no ricci tag in ricci response"
+    sys.exit(1)
+
 def verify_authentication(dom):
     ricci =  dom.getElementsByTagName("ricci")
     if len(ricci) > 0:
@@ -2454,6 +2466,10 @@ def check_authentication(host):
         print "Unable to authenticate with ricci node, please check password."
         sys.exit(1)
 
+    if (not verify_authentication_password(dom)):
+        print "This node is already authorized, but a bad password was provided. (try not using the '-p' option)"
+        sys.exit(1)
+
 def send_ricci_command(module, command, host = None, *vars):
     global password
     variables = ""
-- 
2.1.0

